version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
    environment:
      - FLASK_APP=app/__init__.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/budgeting_db
      - RUNNING_IN_DOCKER=True
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "sleep 5 && flask run --host=0.0.0.0"

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=budgeting_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: